volumes:
  redis-data:
  caddy_config:
  caddy_data:
  prometheus-data:
  grafana-data:
  loki-data:

services:
  app:
    build: .
    stop_grace_period: 1s
    restart: unless-stopped
    ports:
      - 1888
    depends_on:
      - redis

  redis:
    image: "redis:8-alpine"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config

  node-exporter:
    image: prom/node-exporter:v1-distroless
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3-distroless
    restart: unless-stopped
    depends_on:
      - app
      - caddy
      - node-exporter
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:13.1-slim
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:3
    restart: unless-stopped
    volumes:
      - loki-data:/loki
