volumes:
  redis-data:
  caddy_config:
  caddy_data:
  prometheus-data:

services:
  app:
    build: .
    stop_grace_period: 1s
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    ports:
      - 1888
    depends_on:
      - redis

  redis:
    image: "redis:8-alpine"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
      - ./static/lego:/lego

  prometheus:
    image: prom/prometheus:v2.55.0
    restart: unless-stopped
    depends_on:
      - caddy
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
