global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "caddy"
    static_configs:
      - targets: ["caddy:2019"]

  - job_name: "app"
    static_configs:
      - targets: ["app:1888"]

  - job_name: "node-exporter"
    params:
      collect[]:
        - cpu
        - meminfo
    static_configs:
      - targets: ["node-exporter:9100"]
